"""Policy-as-code export — kernel invariants as OPA Rego + Cedar policies.

Enterprise credibility: the same deterministic gates that run in-process
can be enforced in CI (OPA) and at request time (Cedar).
"""

from __future__ import annotations

REGO_POLICY = """package iam.least_privilege

# Generated by PS10 IAM Mitigator — mirrors the 11 Security Kernel invariants.
# Evaluate: opa eval -d iam.rego -i tfplan.json 'data.iam.least_privilege.deny'

default allow := false

deny[msg] {
    some i
    input.proposed_permissions[i] == "*"
    msg := "NO_PRIVILEGE_EXPANSION: wildcard grant prohibited"
}

deny[msg] {
    some i
    input.proposed_permissions[i] in {"iam:*", "iam:CreateRole", "iam:PassRole"}
    msg := "NO_PROTECTED_PERMISSION_MUTATION: admin capability is protected"
}

deny[msg] {
    input.target_provider != input.source_provider
    msg := "NO_CROSS_PROVIDER_MUTATION: cross-cloud mutation halted"
}

deny[msg] {
    input.blast_radius in {"HIGH", "CRITICAL"}
    not input.human_approved
    msg := "NO_UNAPPROVED_HIGH_RISK: human approval required"
}

deny[msg] {
    not input.simulation_passed
    msg := "NO_MUTATION_WITHOUT_SIMULATION: counterfactual simulation must pass"
}

deny[msg] {
    not input.verification_passed
    msg := "NO_COMPLETION_WITHOUT_VERIFICATION: independent verification required"
}

allow {
    count(deny) == 0
}
"""

CEDAR_POLICY = """// Generated by PS10 IAM Mitigator — Cedar equivalent of kernel gates.
// Enforce with: cedar authorize --policies iam.cedar --request-json req.json

permit(
    principal is IAM::Role,
    action in [IAM::Action::"AssumeRole", IAM::Action::"ApplyPolicy"],
    resource is IAM::Policy
) when {
    // NO_PRIVILEGE_EXPANSION: no new wildcards vs baseline
    !context.proposed_has_wildcard &&
    // NO_PROTECTED_PERMISSION_MUTATION
    !context.touches_protected_permission &&
    // NO_CROSS_PROVIDER_MUTATION
    context.source_provider == context.target_provider &&
    // Simulation + verification gates
    context.simulation_passed && context.verification_passed &&
    // Blast radius gate
    !(context.blast_radius in ["HIGH", "CRITICAL"] && !context.human_approved)
};

forbid(
    principal is IAM::Role,
    action == IAM::Action::"ApplyPolicy",
    resource is IAM::Policy
) when {
    context.touches_protected_resource || context.stale_baseline
};
"""


def get_rego() -> str:
    return REGO_POLICY


def get_cedar() -> str:
    return CEDAR_POLICY


__all__ = ["get_rego", "get_cedar", "REGO_POLICY", "CEDAR_POLICY"]
