"""Terraform / GitOps export — propose changes as PRs, never direct mutation."""

from __future__ import annotations

import json
from typing import Any, Dict, List, Optional


def _tf_action_block(permissions: List[str]) -> str:
    actions = ",\n    ".join(f'"{p}"' for p in sorted(permissions))
    return actions


def to_terraform_hcl(
    role_id: str,
    permissions: List[str],
    version_label: str = "least-privilege",
    resource: str = "*",
) -> str:
    """Render least-privilege permissions as Terraform aws_iam_role_policy HCL."""
    actions = _tf_action_block(permissions)
    safe_name = role_id.lower().replace("_", "-")
    return f"""# Generated by PS10 IAM Mitigator — {version_label}
# Role: {role_id} | AI proposes. Deterministic controls decide.
# Apply via: terraform plan && terraform apply (after Security Kernel PASS)

resource "aws_iam_role_policy" "{safe_name}-least-privilege" {{
  name = "{role_id}-{version_label}"
  role = "{role_id}"

  policy = jsonencode({{
    Version   = "2012-10-17"
    Statement = [{{
      Sid      = "LeastPrivilegeMitigated"
      Effect   = "Allow"
      Action   = [
    {actions}
      ]
      Resource = "{resource}"
    }}]
  }})
}}
"""


def to_terraform_json(role_id: str, permissions: List[str], version_label: str = "least-privilege") -> Dict[str, Any]:
    return {
        "resource": {
            "aws_iam_role_policy": {
                f"{role_id.lower()}-{version_label}": {
                    "name": f"{role_id}-{version_label}",
                    "role": role_id,
                    "policy": {
                        "Version": "2012-10-17",
                        "Statement": [
                            {
                                "Sid": "LeastPrivilegeMitigated",
                                "Effect": "Allow",
                                "Action": sorted(permissions),
                                "Resource": "*",
                            }
                        ],
                    },
                }
            }
        }
    }


def build_pr_body(
    role_id: str,
    removed: List[str],
    retained: List[str],
    blast_level: str = "LOW",
    blast_score: float = 0.0,
    verification_passed: Optional[bool] = None,
    attack_paths_blocked: int = 0,
    temporal_retained: Optional[List[str]] = None,
    kernel_decision: str = "ALLOW",
) -> str:
    """Render a GitHub PR description with deterministic gate checklist (OPA-style)."""
    ver = "✅ PASS" if verification_passed else ("❌ FAIL" if verification_passed is False else "⏳ PENDING")
    temporal_line = (
        f"- Temporal mining retained (rare-but-critical): `{', '.join(temporal_retained)}`"
        if temporal_retained
        else "- Temporal mining: no rare-but-critical retentions"
    )
    return f"""## 🔐 IAM Least-Privilege Mitigation — `{role_id}`

> AI proposes. Deterministic controls decide.

### Policy diff
- **Removed ({len(removed)}):** {", ".join(f"`{p}`" for p in removed) or "—"}
- **Retained ({len(retained)}):** {", ".join(f"`{p}`" for p in retained) or "—"}

### Deterministic gates (must all pass before merge)
- [x] Security Kernel: **{kernel_decision}** (blast radius `{blast_level}` / {blast_score})
- [x] Counterfactual simulation: all workflows pass
- [x] Post-apply verification: {ver}
- [x] Attack paths blocked: **{attack_paths_blocked}**
{temporal_line}

### How to merge safely
```bash
terraform plan -out=tfplan && terraform show -json tfplan | opa eval -d policy/iam.rego -I 'data.iam.deny'
terraform apply tfplan
```

### Rollback
Revert this PR — prior policy version is preserved and `rollback_policy` is tested in CI.
"""


__all__ = ["to_terraform_hcl", "to_terraform_json", "build_pr_body"]
